# Generated by Django 4.2.8 on 2023-12-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_number', models.CharField(max_length=50)),
                ('address_line', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('model_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('manufacture_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devicedata',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_timestamp', models.DateTimeField(blank=True, null=True)),
                ('event_label', models.CharField(max_length=100)),
                ('event_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'devicedata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Energyprices',
            fields=[
                ('zipcode', models.IntegerField(primary_key=True, serialize=False)),
                ('price_timestamp', models.DateTimeField()),
                ('price_per_kwh', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'db_table': 'energyprices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrolleddevices',
            fields=[
                ('enrolled_device_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'enrolleddevices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicelocations',
            fields=[
                ('sl_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('apt_area', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('num_bedrooms', models.IntegerField(blank=True, null=True)),
                ('num_occupants', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicelocations',
                'managed': False,
            },
        ),
    ]
