# Generated by Django 5.0 on 2023-12-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='energyprices',
            table='energy_prices',
        ),
    ]
